services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  # app:
  #   build: .
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - db
volumes:
  db_data: